version: "2"
services:
  websocket:
    container_name: websocket
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - redis-websocket
  redis-websocket:
    container_name: redis-websocket
    image: redis
    ports:
      - "8000:8000"
